### ISSUE TITLE
Add a way to get prefered field type

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio_client#7]
#### Describe your issue

To render other controltypes we need a way to get the `prefered` controltype.

See https://github.com/process-engine/charon/pull/65

#### How can others reproduce the issue?

n/a

#### Possible solution

Add a field `preferedControl` to each `field`

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment]
The way to get the prefered controltype is to look at the `formProperties` from the enum formField.
If there is a property with `"name": "uiName"` and `"value": "RadioBox"` we know a radiobox is wanted.
